import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface AnalyticsData {
    totalMessages: number;
    totalConversations: number;
    messagesThisMonth: number;
    dailyMessages: { date: string; count: number }[];
    topQuestions: string[];
}

export function exportAnalyticsToPDF(
    data: AnalyticsData,
    workspaceName: string = 'Workspace'
) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Header with HiHobbes branding
    doc.setFillColor(217, 241, 158); // Pastel green
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Analytics Report', 20, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`${workspaceName} • ${format(new Date(), 'MMMM dd, yyyy')}`, 20, 33);

    // Summary Statistics
    let yPos = 55;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary Statistics', 20, yPos);

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const stats = [
        ['Total Messages', data.totalMessages.toString()],
        ['Total Conversations', data.totalConversations.toString()],
        ['Messages This Month', data.messagesThisMonth.toString()],
        ['Average Response Time', '< 1s'],
    ];

    autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value']],
        body: stats,
        theme: 'grid',
        headStyles: {
            fillColor: [0, 0, 0],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            lineWidth: 0.5,
            lineColor: [0, 0, 0],
        },
        bodyStyles: {
            lineWidth: 0.5,
            lineColor: [0, 0, 0],
        },
        alternateRowStyles: {
            fillColor: [189, 221, 252], // Pastel blue
        },
        margin: { left: 20, right: 20 },
    });

    // Daily Messages Chart (as table)
    yPos = (doc as any).lastAutoTable.finalY + 15;

    if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Daily Message Volume (Last 30 Days)', 20, yPos);

    yPos += 5;

    const chartData = data.dailyMessages.slice(-30).map(item => [
        format(new Date(item.date), 'MMM dd'),
        item.count.toString()
    ]);

    autoTable(doc, {
        startY: yPos,
        head: [['Date', 'Messages']],
        body: chartData,
        theme: 'grid',
        headStyles: {
            fillColor: [189, 221, 252], // Pastel blue
            textColor: [0, 0, 0],
            fontStyle: 'bold',
            lineWidth: 0.5,
            lineColor: [0, 0, 0],
        },
        bodyStyles: {
            lineWidth: 0.5,
            lineColor: [0, 0, 0],
            fontSize: 8,
        },
        margin: { left: 20, right: 20 },
        pageBreak: 'auto',
    });

    // Top Questions
    yPos = (doc as any).lastAutoTable.finalY + 15;

    if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Top Recent Questions', 20, yPos);

    yPos += 5;

    const questions = data.topQuestions.slice(0, 10).map((q, idx) => [
        (idx + 1).toString(),
        q
    ]);

    if (questions.length > 0) {
        autoTable(doc, {
            startY: yPos,
            head: [['#', 'Question']],
            body: questions,
            theme: 'grid',
            headStyles: {
                fillColor: [217, 241, 158], // Pastel green
                textColor: [0, 0, 0],
                fontStyle: 'bold',
                lineWidth: 0.5,
                lineColor: [0, 0, 0],
            },
            bodyStyles: {
                lineWidth: 0.5,
                lineColor: [0, 0, 0],
            },
            columnStyles: {
                0: { cellWidth: 15 },
                1: { cellWidth: 'auto' },
            },
            margin: { left: 20, right: 20 },
        });
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Page ${i} of ${totalPages} • Generated by AI Support Agent`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    doc.save(`analytics-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}

export function exportAnalyticsToCSV(
    data: AnalyticsData,
    workspaceName: string = 'Workspace'
) {
    const rows: string[][] = [];

    // Header
    rows.push([`Analytics Report - ${workspaceName}`]);
    rows.push([`Generated: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}`]);
    rows.push([]);

    // Summary Statistics
    rows.push(['Summary Statistics']);
    rows.push(['Metric', 'Value']);
    rows.push(['Total Messages', data.totalMessages.toString()]);
    rows.push(['Total Conversations', data.totalConversations.toString()]);
    rows.push(['Messages This Month', data.messagesThisMonth.toString()]);
    rows.push(['Average Response Time', '< 1s']);
    rows.push([]);

    // Daily Messages
    rows.push(['Daily Message Volume']);
    rows.push(['Date', 'Messages']);
    data.dailyMessages.forEach(item => {
        rows.push([item.date, item.count.toString()]);
    });
    rows.push([]);

    // Top Questions
    rows.push(['Top Recent Questions']);
    rows.push(['#', 'Question']);
    data.topQuestions.slice(0, 10).forEach((q, idx) => {
        rows.push([(idx + 1).toString(), q]);
    });

    // Convert to CSV string
    const csvContent = rows.map(row =>
        row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')
    ).join('\n');

    // Create and download file
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', `analytics-report-${format(new Date(), 'yyyy-MM-dd')}.csv`);
    link.style.visibility = 'hidden';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}
